#!/bin/bash -e

systemctl daemon-reload >/dev/null 2>&1

if ! getent group minimega >/dev/null 2>&1; then
    echo "Adding minimega group."
    groupadd --system minimega
else
    echo "minimega group already exists."
fi

chgrp -R minimega /usr/share/doc/minimega
chgrp -R minimega /opt/minimega
